namespace SPublisher.Core
{
    public enum SPublisherEvent
    {
        SPublisherStarted,
        SPublisherCompleted,
        BuildExecutionStarted,
        BuildExecutionCompleted,
        BuildStepExecutionStarted,
        BuildStepExecutionCompleted,
        BuildStepExecutionCompletedWithError,
        BuildStepWasSkipped,
        IisManagementStarted,
        IisManagementCompleted,
        DatabaseCreationStarted,
        DatabaseCreationCompleted,
        ApplicationPoolExists,
        ApplicationPoolCreated,
        DatabaseExists,
        DatabaseCreated,
        SiteExists,
        SiteCreated,
        ApplicationExists,
        ApplicationCreated,
        VirtualDirectoryExists,
        VirtualDirectoryCreated,
        ApplicationListIsEmpty,
        InvalidJson,
        SpublisherJsonNotFound,
        UnknownError,
        BuildStepTypeNotFound,
        BuildStepTypeIsMissing,
        CommandLineCouldNotStart,
        ShouldRunAsAdministrator,
        ValidationErrors
    }
}